# Generated by Django 3.1.4 on 2021-02-10 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additionuserinfo',
            name='last_website_visited',
        ),
        migrations.AddField(
            model_name='additionuserinfo',
            name='timezone',
            field=models.CharField(default='Europe/Moscow', max_length=128),
        ),
    ]
