# Generated by Django 3.1.5 on 2021-01-25 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vote_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoteChangeRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('image', models.ImageField(blank=True, null=True, upload_to='voting_images/')),
                ('description', models.TextField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('result_see_who', models.IntegerField(choices=[(0, 'Всем'), (1, 'Проголосовавшим')], default=0, null=True)),
                ('result_see_when', models.IntegerField(choices=[(0, 'В любое время'), (1, 'После окончания')], default=0, null=True)),
                ('variants_count', models.IntegerField(default=2)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField()),
                ('voting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote_app.votings')),
            ],
        ),
        migrations.CreateModel(
            name='VoteVariantsChangeRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.IntegerField()),
                ('description', models.TextField()),
                ('votes_count', models.IntegerField()),
                ('voting_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moderation_app.votechangerequest')),
            ],
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.IntegerField(choices=[(0, 'Жалоба на голосование'), (1, 'Сообщение об ошибке')], default=0)),
                ('element', models.IntegerField(blank=True, null=True)),
                ('content', models.TextField()),
                ('status', models.IntegerField(choices=[(0, 'Обрабатывается'), (1, 'Решена'), (2, 'Отклонена')], default=0)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('close_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
