# Generated by Django 3.1.4 on 2021-01-22 19:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('moderation_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reports',
            name='close_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reports',
            name='element',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reports',
            name='status',
            field=models.IntegerField(choices=[(0, 'Обрабатывается'), (1, 'Решена'), (2, 'Отклонена')], default=0),
        ),
        migrations.AlterField(
            model_name='reports',
            name='theme',
            field=models.IntegerField(choices=[(0, 'Жалоба на голосование'), (1, 'Сообщение об ошибке')], default=0),
        ),
    ]
