# Generated by Django 3.1.4 on 2021-01-06 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moderation_app', '0002_auto_20201230_1604'),
        ('moderation_app', '0002_reports_create_date'),
    ]

    operations = [
    ]
