# Generated by Django 3.1.4 on 2021-01-22 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moderation_app', '0002_auto_20210122_2211'),
        ('moderation_app', '0002_auto_20210122_2227'),
    ]

    operations = [
    ]
