# Generated by Django 3.1.4 on 2021-01-06 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation_app', '0003_merge_20210106_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports',
            name='status',
            field=models.IntegerField(choices=[(0, 'Обрабатывается'), (1, 'Решена'), (2, 'Отклонена')]),
        ),
    ]
