# Generated by Django 3.1.4 on 2021-01-24 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation_app', '0003_merge_20210122_2228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='votechangerequest',
            old_name='change',
            new_name='description',
        ),
        migrations.AddField(
            model_name='votechangerequest',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='votechangerequest',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='voting_images/'),
        ),
        migrations.AddField(
            model_name='votechangerequest',
            name='result_see_when',
            field=models.IntegerField(choices=[(0, 'В любое время'), (1, 'После окончания')], default=0, null=True),
        ),
        migrations.AddField(
            model_name='votechangerequest',
            name='result_see_who',
            field=models.IntegerField(choices=[(0, 'Всем'), (1, 'Проголосовавшим')], default=0, null=True),
        ),
        migrations.AddField(
            model_name='votechangerequest',
            name='title',
            field=models.CharField(default='Title', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='votechangerequest',
            name='variants_count',
            field=models.IntegerField(default=2),
        ),
    ]
