# Generated by Django 3.1.4 on 2021-01-16 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation_app', '0004_auto_20210106_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports',
            name='theme',
            field=models.IntegerField(choices=[(0, 'Жалоба на голосование'), (1, 'Сообщение об ошибке')]),
        ),
    ]
