# Generated by Django 3.1.4 on 2021-01-25 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moderation_app', '0004_auto_20210124_1753'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoteVariantsChangeRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.IntegerField()),
                ('description', models.TextField()),
                ('votes_count', models.IntegerField()),
                ('voting_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moderation_app.votechangerequest')),
            ],
        ),
    ]
