# Generated by Django 3.1.4 on 2021-01-16 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vote_app', '0006_auto_20210114_1618'),
        ('moderation_app', '0005_auto_20210116_1057'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoteChangeRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Change', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField()),
                ('voting_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote_app.votings')),
            ],
        ),
    ]
