# Generated by Django 3.1.4 on 2021-01-16 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moderation_app', '0006_votechangerequest'),
        ('moderation_app', '0007_auto_20210116_1654'),
    ]

    operations = [
    ]
