# Generated by Django 3.1.4 on 2021-01-21 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moderation_app', '0008_merge_20210116_2155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='votechangerequest',
            old_name='Change',
            new_name='change',
        ),
    ]
