# Generated by Django 3.1.4 on 2021-01-21 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moderation_app', '0009_auto_20210121_1038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='votechangerequest',
            old_name='voting_id',
            new_name='voting',
        ),
    ]
