# Generated by Django 3.1.4 on 2020-12-26 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionUserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votings_created', models.IntegerField(default=0)),
                ('number_of_votes_by_user', models.IntegerField(default=0)),
                ('user_patronymic', models.CharField(default='', max_length=128)),
                ('user_rights', models.IntegerField(choices=[(0, 'SIMPLE'), (1, 'MODERATOR'), (2, 'ADMIN')], default=0)),
                ('last_website_visited', models.URLField()),
                ('User_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
