# Generated by Django 3.1.4 on 2021-01-26 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionUserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votings_created', models.IntegerField(default=0)),
                ('votes_given', models.IntegerField(default=0)),
                ('user_rights', models.IntegerField(choices=[(0, 'Обычный'), (1, 'Модератор'), (2, 'Администратор')], default=0)),
                ('last_website_visited', models.URLField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
