# Generated by Django 3.1.4 on 2021-01-06 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionuserinfo',
            name='user_rights',
            field=models.IntegerField(choices=[(0, 'Обычный'), (1, 'Модератор'), (2, 'Администратор')], default=0),
        ),
    ]
