# Generated by Django 3.1.4 on 2021-01-21 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0002_auto_20210106_1807'),
    ]

    operations = [
        migrations.RenameField(
            model_name='additionuserinfo',
            old_name='User_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='additionuserinfo',
            old_name='number_of_votes_by_user',
            new_name='votes_given',
        ),
        migrations.RemoveField(
            model_name='additionuserinfo',
            name='user_patronymic',
        ),
    ]
