# Generated by Django 3.1.4 on 2021-01-26 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Votings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('image', models.ImageField(blank=True, null=True, upload_to='voting_images/')),
                ('description', models.TextField()),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('complaint_state', models.IntegerField(choices=[(0, 'Отсутствует'), (1, 'На рассмотрении'), (2, 'Забанено')], default=0)),
                ('result_see_who', models.IntegerField(choices=[(0, 'Всем'), (1, 'Проголосовавшим')], default=0, null=True)),
                ('result_see_when', models.IntegerField(choices=[(0, 'В любое время'), (1, 'После окончания')], default=0, null=True)),
                ('anons_can_vote', models.BooleanField(default=False)),
                ('type', models.IntegerField(choices=[(0, 'Один вариант'), (1, 'Много вариантов')], default=0)),
                ('voters_count', models.IntegerField(default=0)),
                ('votes_count', models.IntegerField(default=0)),
                ('variants_count', models.IntegerField(default=2)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VoteVariants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.IntegerField()),
                ('description', models.TextField()),
                ('votes_count', models.IntegerField()),
                ('voting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote_app.votings')),
            ],
        ),
        migrations.CreateModel(
            name='Votes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(max_length=256, null=True)),
                ('vote_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote_app.votevariants')),
                ('voting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote_app.votings')),
            ],
        ),
    ]
