# Generated by Django 3.1.4 on 2020-12-26 13:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Votings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=256)),
                ('Image', models.FileField(upload_to='')),
                ('Description', models.TextField()),
                ('CreationDate', models.DateTimeField()),
                ('EndDate', models.DateTimeField()),
                ('ComplaintState', models.IntegerField(choices=[(0, 'Absent'), (1, 'in_progress'), (2, 'banned')], default=0)),
                ('ResultSeeWho', models.IntegerField(choices=[(0, 'All'), (1, 'Voted')], default=0)),
                ('ResultSeeWhen', models.IntegerField(choices=[(0, 'All'), (1, 'Voted')], default=0)),
                ('AnonsCanVote', models.BooleanField()),
                ('Type', models.IntegerField(choices=[(0, 'One'), (1, 'Many')], default=0)),
                ('Votes', models.IntegerField()),
                ('Author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
