# Generated by Django 3.1.4 on 2020-12-26 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vote_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoteVariants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Serial_number', models.IntegerField()),
                ('Description', models.TextField()),
                ('Counts_of_votes', models.IntegerField()),
                ('ID_voting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote_app.votings')),
            ],
        ),
    ]
