# Generated by Django 3.1.4 on 2020-12-30 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote_app', '0003_auto_20201226_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votings',
            name='AnonsCanVote',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='votings',
            name='ComplaintState',
            field=models.IntegerField(choices=[(0, 'Отсутствует'), (1, 'На рассмотрении'), (2, 'Забанено')], default=0),
        ),
        migrations.AlterField(
            model_name='votings',
            name='Image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='votings',
            name='ResultSeeWhen',
            field=models.IntegerField(choices=[(0, 'В любое время'), (1, 'После окончания')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='votings',
            name='ResultSeeWho',
            field=models.IntegerField(choices=[(0, 'Всем'), (1, 'Проголосовавшим')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='votings',
            name='Type',
            field=models.IntegerField(choices=[(0, 'Один вариант'), (1, 'Много вариантов')], default=0),
        ),
        migrations.AlterField(
            model_name='votings',
            name='Votes',
            field=models.IntegerField(default=0),
        ),
    ]
