# Generated by Django 3.1.4 on 2021-01-14 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote_app', '0004_auto_20201230_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votings',
            name='EndDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='votings',
            name='Image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
