# Generated by Django 3.1.4 on 2021-01-14 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote_app', '0005_auto_20210114_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votings',
            name='EndDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='votings',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
