# Generated by Django 3.1.4 on 2021-01-16 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote_app', '0006_auto_20210114_1618'),
    ]

    operations = [
        migrations.RenameField(
            model_name='votes',
            old_name='Choices_id',
            new_name='Variant_id',
        ),
        migrations.RenameField(
            model_name='votes',
            old_name='Votings_id',
            new_name='Voting_id',
        ),
        migrations.RenameField(
            model_name='votevariants',
            old_name='Counts_of_votes',
            new_name='Votes_count',
        ),
        migrations.RenameField(
            model_name='votings',
            old_name='AnonsCanVote',
            new_name='Anons_can_vote',
        ),
        migrations.RenameField(
            model_name='votings',
            old_name='ComplaintState',
            new_name='Complaint_state',
        ),
        migrations.RenameField(
            model_name='votings',
            old_name='CreationDate',
            new_name='Creation_date',
        ),
        migrations.RenameField(
            model_name='votings',
            old_name='EndDate',
            new_name='End_date',
        ),
        migrations.RenameField(
            model_name='votings',
            old_name='ResultSeeWhen',
            new_name='Result_see_when',
        ),
        migrations.RenameField(
            model_name='votings',
            old_name='ResultSeeWho',
            new_name='Result_see_who',
        ),
        migrations.RenameField(
            model_name='votings',
            old_name='Votes',
            new_name='Vote_variants',
        ),
    ]
