# Generated by Django 3.1.4 on 2021-01-17 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote_app', '0007_auto_20210116_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votings',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='voting_images/'),
        ),
    ]
