# Generated by Django 3.1.4 on 2021-01-17 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote_app', '0008_auto_20210117_1725'),
    ]

    operations = [
        migrations.RenameField(
            model_name='votings',
            old_name='Vote_variants',
            new_name='Votes_count',
        ),
        migrations.AddField(
            model_name='votings',
            name='Variants_count',
            field=models.IntegerField(default=2),
        ),
    ]
