# Generated by Django 3.1.4 on 2021-01-21 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote_app', '0009_auto_20210117_2010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='votes',
            old_name='User_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='votes',
            old_name='Variant_id',
            new_name='variant',
        ),
        migrations.RenameField(
            model_name='votes',
            old_name='Date_vote',
            new_name='vote_date',
        ),
        migrations.RenameField(
            model_name='votes',
            old_name='Voting_id',
            new_name='voting',
        ),
        migrations.RenameField(
            model_name='votevariants',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='votevariants',
            old_name='Serial_number',
            new_name='serial_number',
        ),
        migrations.RenameField(
            model_name='votevariants',
            old_name='Votes_count',
            new_name='votes_count',
        ),
        migrations.RenameField(
            model_name='votevariants',
            old_name='ID_voting',
            new_name='voting',
        ),
        migrations.RenameField(
            model_name='votings',
            old_name='Anons_can_vote',
            new_name='anons_can_vote',
        ),
        migrations.RenameField(
            model_name='votings',
            old_name='Author',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='votings',
            old_name='Complaint_state',
            new_name='complaint_state',
        ),
        migrations.RenameField(
            model_name='votings',
            old_name='Creation_date',
            new_name='creation_date',
        ),
        migrations.RenameField(
            model_name='votings',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='votings',
            old_name='End_date',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='votings',
            old_name='Image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='votings',
            old_name='Result_see_when',
            new_name='result_see_when',
        ),
        migrations.RenameField(
            model_name='votings',
            old_name='Result_see_who',
            new_name='result_see_who',
        ),
        migrations.RenameField(
            model_name='votings',
            old_name='Title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='votings',
            old_name='Type',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='votings',
            old_name='Variants_count',
            new_name='variants_count',
        ),
        migrations.RenameField(
            model_name='votings',
            old_name='Votes_count',
            new_name='voters_count',
        ),
    ]
