# Generated by Django 3.1.4 on 2021-01-21 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote_app', '0010_auto_20210121_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='votings',
            name='votes_count',
            field=models.IntegerField(default=0),
        ),
    ]
