# Generated by Django 3.1.4 on 2021-01-21 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote_app', '0012_auto_20210121_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votings',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='voting_images/'),
        ),
    ]
