# Generated by Django 3.1.4 on 2021-01-23 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote_app', '0013_auto_20210121_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='votes',
            name='fingerprint',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
